FROM maven:3.9-amazoncorretto-17-debian

RUN  apt-get update \
  && apt-get install -y wget \
  && rm -rf /var/lib/apt/lists/*

RUN wget -O karate.jar https://github.com/karatelabs/karate/releases/download/v1.4.0/karate-1.4.0.jar

ADD target/repository /usr/share/maven/ref/repository

ADD src /src
ADD pom.xml /pom.xml

EXPOSE 8090
