FROM adoptopenjdk:11-jre-hotspot

RUN curl https://github.com/karatelabs/karate/releases/download/v1.4.0/karate-1.4.0.jar -o karate.jar

ADD target/karate-todo-1.0-SNAPSHOT.jar /app.jar

EXPOSE 8080

CMD ["java", "-cp", "karate.jar:app.jar", "app.App", "classpath:app"]